### ISSUE TITLE
Audio Control Slider

### ISSUE THREAD

**Issue by FSDevi** [App2Sales/react-native-hue-player#12]
The seek bar is showing incorrect number of the audio duration. Please look on the screenshot:
![player](https://user-images.githubusercontent.com/43471273/51530326-af677f00-1e60-11e9-8476-b5a3abaa62d3.jpg)

How to fix this problem?

**Comment by sramezani** [comment]
In "AudioControls/AudioControls.js" file 
line 241:
`{currentTime ? moment(currentTime * 1000).format('mm:ss') : '00:00'}`
change to:
`{currentTime ? moment.utc(currentTime * 1000).format('mm:ss') : '00:00'}`

and line 263:
`{duration ? moment(duration * 1000).format('mm:ss') : '00:00'}`
change to
`{duration ? moment.utc(duration * 1000).format('mm:ss') : '00:00'}`

**Comment by jkdrangel** [comment]
#14
